---
- name: "Install python"
  become: true
  apt:
    name: python3
    state: latest
    update_cache: "yes"
    
- name: "Update/upgrade packages"
  become: true
  apt:
    update_cache: "yes"
    upgrade: "yes"

- name: "Install nodejs, npm"
  become: true
  apt: 
    name: ["nodejs", "npm"]
    state: latest
    update_cache: "yes"

- name: "Install pm2"
  become: true
  npm:
    name: "pm2"
    state: latest 
