---
- name: "Install python"
  become: true
  apt:
    name: python3
    state: latest
    update_cache: "yes"
    
- name: "Update/upgrade packages"
  become: true
  apt:
    update_cache: "yes"
    upgrade: "yes"

- name: "Install nodejs, npm"
  become: true
  shell:
    cmd: "apt install -y nodejs npm"

- name: "Install pm2"
  become: true
  npm:
    name: "pm2"
    global: "yes"
    production: yes
    state: present

# "environment" in the playbook doesn't seem to be working...
- name: "Set environment variables manually"
  become: true
  shell: |
    echo "export TYPEORM_CONNECTION={{ lookup('env', 'TYPEORM_CONNECTION')}}" >> ~/.bashrc  
    echo "export TYPEORM_ENTITIES={{ lookup('env', 'TYPEORM_ENTITIES')}}" >> ~/.bashrc 
    echo "export TYPEORM_HOST={{ lookup('env', 'TYPEORM_HOST')}}" >> ~/.bashrc 
    echo "export TYPEORM_PORT=5432" >> ~/.bashrc 
    echo "export TYPEORM_USERNAME={{ lookup('env', 'TYPEORM_USERNAME')}}" >> ~/.bashrc 
    echo "export TYPEORM_PASSWORD={{ lookup('env', 'TYPEORM_PASSWORD')}}" >> ~/.bashrc 
    echo "export TYPEORM_DATABASE={{ lookup('env', 'TYPEORM_DATABASE')}}" >> ~/.bashrc 
    echo "export TYPEORM_MIGRATIONS={{ lookup('env', 'TYPEORM_MIGRATIONS')}}" >> ~/.bashrc 
    echo "export TYPEORM_MIGRATIONS_DIR={{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}" >> ~/.bashrc 
    source ~/.bashrc