---

- name: "Copy files to server"
  become: true
  copy:
    src: backend/artifact.tar.gz
    dest: /~

- name: "Unzip copied files"
  become: true
  unarchive:
    src: backend/artifact.tar.gz
    dest: /~

- name: "Install nodejs, npm"
  become: true
  shell:
    cmd: "npm install"

- name: "Run pm2"
  become: true
  shell:
    cmd: "pm2 stop default && pm2 start npm -- start"